### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by PeterParslow** [arnau/addresspack#3]
You may be pleased to note that AddressBase Core is now available in GeoPackage, and AddressBase Premium should follow suit.

AddressBase Core has a simplified schema, suitable for many use cases.

GeoPackage is the OGC open standard that builds on SQL Lite.

Yes, I work for OS - thanks Arnau for the pointer / criticism!

**Comment by arnau** [comment]
@PeterParslow this is excellent news, thanks :)
